### ISSUE TITLE
Borrar una pregunta

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#69]
Cuando pulso delete en una pregunta da error y en la terminal se viualiza:

/home/ldonoso/decidder-new/node_modules/babel/node_modules/mongodb/lib/mongodb/connection/server.js:485
        throw err;
              ^
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:708:11)
    at ServerResponse.res.setHeader (/home/ldonoso/decidder-new/node_modules/babel/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at ServerResponse.res.set.res.header (/home/ldonoso/decidder-new/node_modules/babel/node_modules/express/lib/response.js:513:10)
    at ServerResponse.res.send (/home/ldonoso/decidder-new/node_modules/babel/node_modules/express/lib/response.js:124:10)
    at ServerResponse.res.json (/home/ldonoso/decidder-new/node_modules/babel/node_modules/express/lib/response.js:191:15)
    at /home/ldonoso/decidder-new/routes/question.js:176:19
    at /home/ldonoso/decidder-new/node_modules/babel/models/dbitem.js:46:5
    at /home/ldonoso/decidder-new/node_modules/babel/lib/db.js:21:6
    at /home/ldonoso/decidder-new/node_modules/babel/lib/db.js:58:13
    at null.<anonymous> (/home/ldonoso/decidder-new/node_modules/babel/node_modules/mongodb/lib/mongodb/collection.js:466:9)

**Comment by joserobleda** [comment]
debe estar solucionado por que ya no pasa...
