### ISSUE TITLE
Error al loguear con twitter

### ISSUE THREAD

**Issue by LdonosoC** [joserobleda/decidder-new#73]
Al intentar loguearme con twitter, en algunas ocasiones me da error.
En la consola indica:

/home/ldonoso/decidder-new/node_modules/babel/lib/request.js:8
            cb(err, response.request.href);
                            ^
TypeError: Cannot read property 'request' of undefined
    at Request._callback (/home/ldonoso/decidder-new/node_modules/babel/lib/request.js:8:20)
    at self.callback (/home/ldonoso/decidder-new/node_modules/babel/node_modules/request/main.js:122:22)
    at Request.EventEmitter.emit (events.js:95:17)
    at ClientRequest.self.clientErrorHandler (/home/ldonoso/decidder-new/node_modules/babel/node_modules/request/main.js:225:10)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at CleartextStream.socketOnData (http.js:1533:9)
    at CleartextStream.read [as _read](tls.js:460:10)
    at CleartextStream.Readable.read (_stream_readable.js:293:10)
    at EncryptedStream.write [as _write](tls.js:330:25)
    at doWrite (_stream_writable.js:211:10)
    at writeOrBuffer (_stream_writable.js:201:5)
    at EncryptedStream.Writable.write (_stream_writable.js:172:11)

**Comment by pdelmoral** [comment]
A mi también me salía esta issue pero lleva todo el finde sin salirme... os sigue pasando?
